"""Generate snappyHexMeshDict snippets for urban CFD cases."""

from __future__ import annotations

from pathlib import Path


def _foam_tuple_xyz(x: float, y: float, z: float) -> str:
    return f"({x:.6g} {y:.6g} {z:.6g})"


def _foam_bounds_pair(
    xmin: float,
    ymin: float,
    zmin: float,
    xmax: float,
    ymax: float,
    zmax: float,
) -> str:
    return f"{_foam_tuple_xyz(xmin, ymin, zmin)}{_foam_tuple_xyz(xmax, ymax, zmax)}"


def _pick_stl(stl_files: dict[str, Path | str], *names: str) -> tuple[str, str] | None:
    for name in names:
        path = stl_files.get(name)
        if path and Path(path).is_file():
            return name, Path(path).name
    return None


def write_snappy_hex_mesh_dict(
    output_path: str | Path,
    *,
    stl_files: dict[str, Path | str],
    outer_bounds: dict[str, float],
    refinement_box: tuple[float, float, float, float, float, float],
    inside_point: tuple[float, float, float],
    block_cells: tuple[int, int, int] = (40, 16, 8),
    surface_levels: tuple[int, int] = (3, 4),
    feature_level: int = 3,
) -> dict:
    """
    Write a starter ``snappyHexMeshDict`` for buildings + terrain STLs.

    Copy into ``constant/triSurface`` and ``system/`` in your OpenFOAM case, run
    ``surfaceFeatureExtract``, then ``snappyHexMesh``.
    """
    output_path = Path(output_path)
    buildings = _pick_stl(stl_files, "buildings_on_dem", "buildings")
    terrain = _pick_stl(stl_files, "terrain")

    if buildings is None:
        raise ValueError("Need buildings.stl or buildings_on_dem.stl for snappyHexMesh")

    b_name, b_file = buildings
    t_name, t_file = (terrain if terrain else (None, None))

    rx0, ry0, rz0, rx1, ry1, rz1 = refinement_box
    ox0, ox1, oy0, oy1 = (
        outer_bounds["x_min"],
        outer_bounds["x_max"],
        outer_bounds["y_min"],
        outer_bounds["y_max"],
    )
    oz0, oz1 = outer_bounds.get("z_min", 0.0), outer_bounds["z_max"]
    ix, iy, iz = inside_point
    nx, ny, nz = block_cells
    lev_min, lev_max = surface_levels

    geometry_blocks = [
        f"""    {b_name}
    {{
        type    triSurfaceMesh;
        file    "{b_file}";
    }}""",
    ]
    if t_name and t_file:
        geometry_blocks.append(
            f"""    {t_name}
    {{
        type    triSurfaceMesh;
        file    "{t_file}";
    }}"""
        )

    feature_entries = [
        f"""      {{
            file "{b_file.replace('.stl', '.eMesh')}";
            level {feature_level};
      }}""",
    ]
    if t_name and t_file:
        feature_entries.append(
            f"""      {{
            file "{t_file.replace('.stl', '.eMesh')}";
            level {feature_level};
      }}"""
        )

    refine_surfaces = [
        f"""        {b_name}
        {{
            level ({lev_min} {lev_max});
            patchInfo
            {{
                type    wall;
            }}
        }}""",
    ]
    if t_name:
        refine_surfaces.append(
            f"""        {t_name}
        {{
            level ({lev_min} {lev_max});
            patchInfo
            {{
                type    wall;
            }}
        }}"""
        )

    text = f"""// Generated by CFDGeometry — merge into your OpenFOAM case system/snappyHexMeshDict
// 1) Copy STLs to constant/triSurface/
// 2) surfaceFeatureExtract
// 3) snappyHexMesh

FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      snappyHexMeshDict;
}}

castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
{chr(10).join(geometry_blocks)}

    refinementBox
    {{
        type    searchableBox;
        min     {_foam_tuple_xyz(rx0, ry0, rz0)};
        max     {_foam_tuple_xyz(rx1, ry1, rz1)};
    }}
}};

castellatedMeshControls
{{
    maxLocalCells 1000000;
    maxGlobalCells 2000000;
    minLevel 0;
    maxLevel 6;

    resolveFeatureAngle 30;

    features
    (
{chr(10).join(feature_entries)}
    );

    refinementSurfaces
    {{
{chr(10).join(refine_surfaces)}
    }}

    refinementRegions
    {{
        refinementBox
        {{
            mode inside;
            levels ((1e15 2));
        }}
    }}

    locationInMesh ({ix:.6g} {iy:.6g} {iz:.6g});
    allowFreeStandingZoneFaces true;
}};

snapControls
{{
    nSmoothPatch 3;
    tolerance 2.0;
    nSolveIter 100;
    nRelaxIter 5;
}};

addLayersControls {{}}

meshQualityControls
{{
    maxNonOrtho 65;
    maxBoundarySkewness 20;
    minVol 1e-13;
    nSmoothScale 4;
    errorReduction 0.75;
}};
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text, encoding="utf-8")

    cmd_path = output_path.parent / "snappyHexMeshConfig.command"
    outer_pair = _foam_bounds_pair(ox0, oy0, oz0, ox1, oy1, oz1)
    ref_line = (
        f"(({rx0:.6g} {ry0:.6g} {rz0:.6g}) "
        f"({rx1:.6g} {ry1:.6g} {rz1:.6g}) 2)"
    )
    stack = max(5.0, 0.25 * min(ox1 - ox0, oy1 - oy0))
    cmd = f"""# Optional: snappyHexMeshConfig one-shot background mesh (OpenFOAM utility)
# Adjust patch names to match blockMeshDict before running.

runApplication snappyHexMeshConfig \\
    -bounds '{outer_pair}' \\
    -nCells '({nx} {ny} {nz})' \\
    -clearBoundary \\
    -xMinPatch 'inlet patch' \\
    -zMinPatch 'ground wall' \\
    -defaultPatch 'outlet patch' \\
    -insidePoint '{_foam_tuple_xyz(ix, iy, iz)}' \\
    -refinementDists '(stack {stack:.6g} {stack:.6g})' \\
    -refinementBoxes '
                         {ref_line}
                     '
"""
    cmd_path.write_text(cmd, encoding="utf-8")
    print(f"snappyHexMeshDict: {output_path}")
    print(f"snappyHexMeshConfig hint: {cmd_path}")

    return {
        "snappy_hex_mesh_dict": str(output_path),
        "snappy_command": str(cmd_path),
        "building_surface": b_name,
        "terrain_surface": t_name,
    }
